const alphabet_hash = [
  {id: 1, character: "А а", name: "ah", implementation: "\"ah\" sound in Cat"},
  {id: 2, character: "Б б", name: "buh", implementation: "\"B\" as in Book"},
  {id: 3, character: "В в", name: "veh", implementation: "\"V\" as in View"},
  {id: 4, character: "Г г", name: "huh", implementation: "\"H\" as in How"},
  {id: 5, character: "Ґ ґ", name: "geh", implementation: "\"G\" as in Gate (rarely used)"},
  {id: 6, character: "Д д", name: "deh", implementation: "\"D\" as in Door"},
  {id: 7, character: "Е е", name: "eh", implementation: "\"eh\" sound in Red"},
  {id: 8, character: "Є є", name: "ye", implementation: "\"Y\" sound as in Yes"},
  {id: 9, character: "Ж ж", name: "zheh", implementation: "\"zh\" sound in Measure"},
  {id: 10, character: "З з", name: "zeh", implementation: "\"Z\" as in Zoo"},
  {id: 11, character: "И и", name: "ih", implementation: "short \"I\" as in Picture (pronounced longer)"},
  {id: 12, character: "І і", name: "ee", implementation: "\"E\" sound in Greet"},
  {id: 13, character: "Ї ї", name: "yih", implementation: "\"yih\" sound as in Year (pronounced longer)"},
  {id: 14, character: "Й й", name: "yot", implementation: "\"yoo\" as in Youth (pronounced shorter)"},
  {id: 15, character: "К к", name: "kah", implementation: "\"K\" as in Keep"},
  {id: 16, character: "Л л", name: "luh", implementation: "\"L\" as in Loose"},
  {id: 17, character: "М м", name: "moh", implementation: "\"M\" as in Moose"},
  {id: 18, character: "Н н", name: "neh", implementation: "\"N\" as in No"},
  {id: 19, character: "О о", name: "oh", implementation: "\"oh\" sound in Goat"},
  {id: 20, character: "П п", name: "puh", implementation: "\"P\" as in Put"},
  {id: 21, character: "Р р", name: "ruh", implementation: "Like the thrilled \"R\" in Spanish or Italian"},
  {id: 22, character: "С с", name: "ceh", implementation: "\"S\" as in Soon"},
  {id: 23, character: "Т т", name: "te", implementation: "\"T\" as in Take"},
  {id: 24, character: "У у", name: "oo", implementation: "\"oo\" sound in Doodle (pronounced longer)"},
  {id: 25, character: "Ф ф", name: "fuh", implementation: "\"F\" as in Forget"},
  {id: 26, character: "Х х", name: "hu", implementation: "\"ch\" sound the Scottish \"loch\""},
  {id: 27, character: "Ц ц", name: "tse", implementation: "\"ts\" sound in Cats"},
  {id: 28, character: "Ч ч", name: "cheh", implementation: "\"ch\" sound in Cheer"},
  {id: 29, character: "Ш ш", name: "sheh", implementation: "\"sh\" sound in Shy"},
  {id: 30, character: "Щ щ", name: "shcha", implementation: "\"sh\" sound in Fresh and \"ch\" sound in Cheese combined - \"shch\""},
  {id: 31, character: "ь", name: "myakih znak (м’який знак)", implementation: "Softens the previous consonant"},
  {id: 32, character: "Ю ю", name: "yoo", implementation: "\"yoo\" sound in United"},
  {id: 33, character: "Я я", name: "yah", implementation: "\"yah\" sound in Yard"},
  {id: 34, character: "'", name: "apostrof (апостроф)", implementation: "Strengthens the following vowel"},
]

export default alphabet_hash;
