const alphabet_hash = [
  {id: 1, character: "А а", name: "ah", implementation: "Cat"},
  {id: 2, character: "Б б", name: "beh", implementation: "Book"},
  {id: 3, character: "В в", name: "weh/veh", implementation: "Vet/When*"},
  {id: 4, character: "Г г", name: "heh", implementation:  "How"},
  {id: 5, character: "Ґ ґ", name: "geh", implementation:  "Gate"},
  {id: 6, character: "Д д", name: "deh", implementation:  "Door"},
  {id: 7, character: "Е е", name: "eh", implementation:  "Red"},
  {id: 8, character: "Є є", name: "yeh", implementation:  "Yes"},
  {id: 9, character: "Ж ж", name: "zheh", implementation:  "Measure"},
  {id: 10, character: "З з", name: "zeh", implementation:  "Zoo"},
  {id: 11, character: "И и", name: "ih", implementation:  "PIt (but longer)"},
  {id: 12, character: "І і", name: "ee", implementation:  "Meet"},
  {id: 13, character: "Ї ї", name: "yih", implementation:  "Year (but longer)"},
  {id: 14, character: "Й й", name: "yot", implementation:  "Yes"},
  {id: 15, character: "К к", name: "kah", implementation:  "Couch"},
  {id: 16, character: "Л л", name: "el", implementation:  "Loose"},
  {id: 17, character: "М м", name: "em", implementation:  "Moose"},
  {id: 18, character: "Н н", name: "en", implementation:  "No"},
  {id: 19, character: "О о", name: "oh", implementation:  "Goat"},
  {id: 20, character: "П п", name: "peh", implementation:  "Put"},
  {id: 21, character: "Р р", name: "er", implementation:  "Like the thrilled r in Spanish or Italian"},
  {id: 22, character: "С с", name: "es", implementation:  "Soon"},
  {id: 23, character: "Т т", name: "te", implementation:  "Take"},
  {id: 24, character: "У у", name: "oo", implementation:  "Do"},
  {id: 25, character: "Ф ф", name: "ef", implementation:  "Forget"},
  {id: 26, character: "Х х", name: "kha", implementation:  "ch in the Scottisch 'loch'"},
  {id: 27, character: "Ц ц", name: "tse", implementation:  "Cats"},
  {id: 28, character: "Ч ч", name: "cheh", implementation:  "Chase"},
  {id: 29, character: "Ш ш", name: "shah", implementation:  "Shy"},
  {id: 30, character: "Щ щ", name: "shcha", implementation:  "Strong/Fish ch*urch"},
  {id: 31, character: "ь", name: "myakih znak (м’який знак)", implementation: "Softens the previous consonant"},
  {id: 32, character: "Ю ю", name: "yoo", implementation: "You"},
  {id: 33, character: "Я я", name: "yah", implementation: "Yard"},
  {id: 34, character: "'", name: "apostrof (апостроф)", implementation: "Strengthens the following vowel"},
]

export default alphabet_hash;
