const alphabet_hash = [
  {character: "А а", name: "ah", implementation: "Cat"},
  {character: "Б б", name: "beh", implementation: "Book"},
  {character: "В в", name: "weh/veh", implementation: "Vet/When*"},
  {character: "Г г", name: "heh", implementation:  "How"},
  {character: "Ґ ґ", name: "geh", implementation:  "Gate"},
  {character: "Д д", name: "deh", implementation:  "Door"},
  {character: "Е е", name: "eh", implementation:  "Red"},
  {character: "Є є", name: "yeh", implementation:  "Yes"},
  {character: "Ж ж", name: "zheh", implementation:  "Measure"},
  {character: "З з", name: "zeh", implementation:  "Zoo"},
  {character: "И и", name: "ih", implementation:  "PIt (but longer)"},
  {character: "І і", name: "ee", implementation:  "Meet"},
  {character: "Ї ї", name: "yih", implementation:  "Year (but longer)"},
  {character: "Й й", name: "yot", implementation:  "Yes"},
  {character: "К к", name: "kah", implementation:  "Couch"},
  {character: "Л л", name: "el", implementation:  "Loose"},
  {character: "М м", name: "em", implementation:  "Moose"},
  {character: "Н н", name: "en", implementation:  "No"},
  {character: "О о", name: "oh", implementation:  "Goat"},
  {character: "П п", name: "peh", implementation:  "Put"},
  {character: "Р р", name: "er", implementation:  "Like the thrilled r in Spanish or Italian"},
  {character: "С с", name: "es", implementation:  "Soon"},
  {character: "Т т", name: "te", implementation:  "Take"},
  {character: "У у", name: "oo", implementation:  "Do"},
  {character: "Ф ф", name: "ef", implementation:  "Forget"},
  {character: "Х х", name: "kha", implementation:  "ch in the Scottisch 'loch'"},
  {character: "Ц ц", name: "tse", implementation:  "Cats"},
  {character: "Ч ч", name: "cheh", implementation:  "Chase"},
  {character: "Ш ш", name: "shah", implementation:  "Shy"},
  {character: "Щ щ", name: "shcha", implementation:  "Strong/Fish ch*urch"},
  {character: "ь", name: "myakih znak (м’який знак)", implementation: "Softens the previous consonant"},
  {character: "Ю ю", name: "yoo", implementation: "You"},
  {character: "Я я", name: "yah", implementation: "Yard"},
  {character: "'", name: "apostrof (апостроф)", implementation: "Strengthens the following vowel"},
]

export default alphabet_hash;
